const citiesByCountry = {
  Andorra: ["Escaldes-Engordany", "Andorra la Vella"],
  "United Arab Emirates": [
    "Umm al Qaywayn",
    "Raʼs al Khaymah",
    "Ash Shāriqah",
    "Dubai",
    "Al Fujayrah",
    "Abu Dhabi",
    "Ajman",
  ],
  Afghanistan: [
    "Nīmrūz",
    "Takhār",
    "Herat",
    "Jowzjān",
    "Ghowr",
    "Sar-e Pol",
    "Samangān",
    "Kunduz",
    "Wilāyat-e Baghlān",
    "Kabul",
    "Faryab",
    "Laghmān",
    "Balkh",
    "Helmand",
    "Khowst",
    "Kandahār",
    "Nangarhār",
    "Parvān",
    "Badghis",
    "Ghaznī",
    "Paktia",
    "Badakhshan",
    "Farah",
    "Lowgar",
    "Bāmīān",
    "Konar",
    "Panjshir",
  ],
  "Antigua and Barbuda": ["Saint John"],
  Anguilla: ["N/A"],
  Albania: [
    "Vlorë",
    "Kukës",
    "Korçë",
    "Gjirokastër",
    "Elbasan",
    "Dibër",
    "Tiranë",
    "Shkodër",
    "Fier",
    "Lezhë",
    "Berat",
    "Durrës",
  ],
  Armenia: [
    "Syunik Province",
    "Ararat Province",
    "Yerevan",
    "Armavir Province",
    "Lori Province",
    "Gegharkunik Province",
    "Kotayk Province",
    "Shirak Province",
    "Aragatsotn Province",
  ],
  Angola: [
    "Lunda Sul",
    "Lunda Norte",
    "Moxico",
    "Uíge",
    "Zaire",
    "Cuanza Norte",
    "Malanje",
    "Luanda",
    "Bengo",
    "Cabinda",
    "Cuanza Sul",
    "Namibe",
    "Cuando Cubango",
    "Huíla",
    "Huambo",
    "Benguela",
    "Bié",
  ],
  Argentina: [
    "Buenos Aires",
    "Santa Fe",
    "Buenos Aires F.D.",
    "Entre Rios",
    "Misiones",
    "Corrientes",
    "Chaco",
    "Formosa",
    "Neuquen",
    "Tucumán",
    "Rio Negro",
    "San Juan",
    "Cordoba",
    "Tierra del Fuego",
    "Chubut",
    "Santiago del Estero",
    "Salta",
    "La Pampa",
    "Jujuy",
    "Mendoza",
    "San Luis",
    "Catamarca",
    "Santa Cruz",
    "La Rioja",
  ],
  "American Samoa": ["Eastern District"],
  Austria: [
    "Carinthia",
    "Lower Austria",
    "Vienna",
    "Upper Austria",
    "Salzburg",
    "Vorarlberg",
    "Styria",
    "Tyrol",
  ],
  Australia: [
    "South Australia",
    "Western Australia",
    "Queensland",
    "Northern Territory",
    "Victoria",
    "New South Wales",
    "Tasmania",
    "Australian Capital Territory",
  ],
  Aruba: ["N/A"],
  "Aland Islands": ["Mariehamns stad"],
  Azerbaijan: [
    "Xankǝndi",
    "Saatlı",
    "Şuşa",
    "Salyan",
    "Neftçala",
    "Nakhichevan",
    "Lənkəran",
    "İmişli",
    "Füzuli",
    "Jalilabad",
    "Bilǝsuvar",
    "Beyləqan",
    "Astara",
    "Shirvan",
    "Ağdam",
    "Zaqatala",
    "Baki",
    "Yevlax City",
    "Goygol Rayon",
    "Xaçmaz",
    "Ucar",
    "Tǝrtǝr",
    "Sumqayit",
    "Şǝmkir",
    "Şamaxı",
    "Shaki City",
    "Sabirabad",
    "Qusar",
    "Quba",
    "Hacıqabul",
    "Qazax",
    "Mingǝcevir",
    "Kürdǝmir",
    "Abşeron",
    "Göyçay",
    "Gǝncǝ",
    "Shabran",
    "Bǝrdǝ",
    "Ağsu",
    "Ağdaş",
    "Ağcabǝdi",
  ],
  "Bosnia and Herzegovina": [
    "Federation of Bosnia and Herzegovina",
    "Republika Srpska",
    "Brčko",
  ],
  Barbados: ["Saint Michael"],
  Bangladesh: [
    "Rangpur Division",
    "Chittagong",
    "Dhaka",
    "Sylhet",
    "Rājshāhi",
    "Khulna",
    "Barisāl",
  ],
  Belgium: ["Flanders", "Wallonia", "Brussels Capital"],
  "Burkina Faso": [
    "Plateau-Central",
    "Nord",
    "Boucle du Mouhoun",
    "Centre-Est",
    "Centre-Ouest",
    "Centre-Sud",
    "Centre",
    "Centre-Nord",
    "High-Basins",
    "Est",
    "Sahel",
    "Cascades",
    "Southwest",
  ],
  Bulgaria: [
    "Yambol",
    "Vratsa",
    "Vidin",
    "Pazardzhik",
    "Veliko Tŭrnovo",
    "Varna",
    "Tŭrgovishte",
    "Lovech",
    "Dobrich",
    "Khaskovo",
    "Stara Zagora",
    "Kyustendil",
    "Sofia-Capital",
    "Smolyan",
    "Sliven",
    "Silistra",
    "Shumen",
    "Gabrovo",
    "Blagoevgrad",
    "Sofiya",
    "Ruse",
    "Razgrad",
    "Plovdiv",
    "Pleven",
    "Pernik",
    "Montana",
    "Kŭrdzhali",
    "Burgas",
  ],
  Bahrain: [
    "Manama",
    "Southern Governorate",
    "Central Governorate",
    "Muharraq",
  ],
  Burundi: [
    "Makamba",
    "Bururi",
    "Bujumbura Mairie",
    "Muramvya",
    "Gitega",
    "Ruyigi",
    "Ngozi",
    "Kayanza",
    "Muyinga",
    "Rutana",
  ],
  Benin: [
    "Borgou",
    "Atakora",
    "Collines",
    "Plateau",
    "Quémé",
    "Atlantique",
    "Mono",
    "Alibori",
    "Kouffo",
    "Donga",
    "Zou",
    "Littoral",
  ],
  "Saint Barthelemy": ["N/A"],
  Bermuda: ["Hamilton city"],
  Brunei: ["Tutong", "Belait", "Brunei and Muara"],
  Bolivia: [
    "Tarija",
    "Santa Cruz",
    "Potosí",
    "El Beni",
    "Chuquisaca",
    "Cochabamba",
    "Oruro",
    "La Paz",
    "Pando",
  ],
  "Bonaire, Saint Eustatius and Saba": ["Bonaire"],
  Brazil: [
    "Maranhão",
    "Pernambuco",
    "Pará",
    "Paraíba",
    "Ceará",
    "Alagoas",
    "Piauí",
    "Rio Grande do Norte",
    "Amapá",
    "Bahia",
    "Amazonas",
    "Tocantins",
    "Santa Catarina",
    "São Paulo",
    "Rio de Janeiro",
    "Espírito Santo",
    "Minas Gerais",
    "Rio Grande do Sul",
    "Paraná",
    "Mato Grosso",
    "Goiás",
    "Mato Grosso do Sul",
    "Sergipe",
    "Federal District",
    "Acre",
    "Rondônia",
    "Roraima",
  ],
  Bahamas: ["New Providence", "Freeport"],
  Bhutan: ["Thimphu", "Punakha", "Chukha District", "Chirang"],
  Botswana: [
    "Central",
    "Kweneng",
    "South East",
    "Southern",
    "Kgatleng",
    "North West",
    "North East",
  ],
  Belarus: [
    "Minsk",
    "Gomel",
    "Vitebsk",
    "Grodnenskaya",
    "Brest",
    "Mogilev",
    "Minsk City",
  ],
  Belize: ["Cayo", "Orange Walk", "Belize"],
  Canada: [
    "British Columbia",
    "Alberta",
    "Ontario",
    "Quebec",
    "Manitoba",
    "Prince Edward Island",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "New Brunswick",
    "Saskatchewan",
    "Yukon",
    "Northwest Territories",
  ],
  "Cocos Islands": ["N/A"],
  "Democratic Republic of the Congo": [
    "Eastern Province",
    "South Kivu",
    "Kasaï-Occidental",
    "Nord Kivu",
    "Kasaï-Oriental",
    "Équateur",
    "Katanga",
    "Maniema",
    "Bas-Congo",
    "Bandundu",
    "Kinshasa",
  ],
  "Central African Republic": [
    "Basse-Kotto",
    "Ouaka",
    "Haute-Kotto",
    "Mbomou",
    "Kémo",
    "Ouham-Pendé",
    "Sangha-Mbaéré",
    "Lobaye",
    "Nana-Grébizi",
    "Ombella-Mpoko",
    "Mambéré-Kadéï",
    "Nana-Mambéré",
    "Ouham",
    "Bangui",
  ],
  "Republic of the Congo": [
    "Lékoumou",
    "Pointe-Noire",
    "Cuvette",
    "Sangha",
    "Niari",
    "Bouenza",
    "Likouala",
    "Plateaux",
    "Brazzaville",
  ],
  Switzerland: [
    "Zurich",
    "Zug",
    "Vaud",
    "Saint Gallen",
    "Aargau",
    "Geneva",
    "Bern",
    "Valais",
    "Schaffhausen",
    "Solothurn",
    "Neuchâtel",
    "Basel-Landschaft",
    "Lucerne",
    "Ticino",
    "Thurgau",
    "Appenzell Ausserrhoden",
    "Fribourg",
    "Grisons",
    "Basel-City",
  ],
  "Ivory Coast": [
    "Marahoué",
    "Lacs",
    "Haut-Sassandra",
    "Bafing",
    "Savanes",
    "Lagunes",
    "Zanzan",
    "Bas-Sassandra",
    "Vallée du Bandama",
    "Fromager",
    "Denguélé",
    "Worodougou",
    "Dix-Huit Montagnes",
    "Sud-Bandama",
    "Sud-Comoé",
    "Nʼzi-Comoé",
    "Moyen-Comoé",
    "Agnéby",
  ],
  "Cook Islands": ["N/A"],
  Chile: [
    "Valparaíso",
    "Araucanía",
    "Atacama",
    "Los Ríos",
    "Biobío",
    "Antofagasta",
    "Maule",
    "Santiago Metropolitan",
    "O'Higgins",
    "Magallanes",
    "Los Lagos",
    "Aisén",
    "Coquimbo",
    "Tarapacá",
    "Arica y Parinacota",
  ],
  Cameroon: [
    "Centre",
    "Far North",
    "North-West Province",
    "West",
    "South-West Province",
    "Adamaoua",
    "North Province",
    "South Province",
    "Littoral",
    "East",
  ],
  China: [
    "Tibet Autonomous Region",
    "Gansu Sheng",
    "Xinjiang Uygur Zizhiqu",
    "Guizhou Sheng",
    "Shandong Sheng",
    "Sichuan",
    "Hunan",
    "Henan Sheng",
    "Shanghai Shi",
    "Zhejiang Sheng",
    "Liaoning",
    "Jiangsu",
    "Yunnan",
    "Hubei",
    "Guangdong",
    "Hebei",
    "Fujian",
    "Shaanxi",
    "Shanxi Sheng",
    "Guangxi Zhuangzu Zizhiqu",
    "Chongqing Shi",
    "Anhui Sheng",
    "Ningxia Huizu Zizhiqu",
    "Jiangxi Sheng",
    "Tianjin Shi",
    "Hainan",
    "Qinghai Sheng",
    "Inner Mongolia",
    "Beijing",
    "Jilin Sheng",
    "Heilongjiang Sheng",
  ],
  Colombia: [
    "Cundinamarca",
    "Valle del Cauca",
    "Antioquia",
    "Casanare",
    "Caldas",
    "Meta",
    "Norte de Santander",
    "La Guajira",
    "Cesar",
    "Bolívar",
    "Nariño",
    "Boyacá",
    "Sucre",
    "Córdoba",
    "Arauca",
    "Atlántico",
    "Santander",
    "Risaralda",
    "Cauca",
    "Magdalena",
    "Archipiélago de San Andrés, Providencia y Santa Catalina",
    "Quindío",
    "Chocó",
    "Putumayo",
    "Huila",
    "Tolima",
    "Amazonas",
    "Caquetá",
    "Bogota D.C.",
    "Guaviare",
  ],
  "Costa Rica": [
    "Cartago",
    "San José",
    "Limón",
    "Alajuela",
    "Heredia",
    "Puntarenas",
    "Guanacaste",
  ],
  Cuba: [
    "Granma",
    "Sancti Spíritus",
    "Pinar del Río",
    "Camagüey",
    "Ciego de Ávila",
    "Matanzas",
    "Holguín",
    "Villa Clara",
    "La Habana",
    "Santiago de Cuba",
    "Mayabeque",
    "Artemisa",
    "Cienfuegos",
    "Guantánamo",
    "Las Tunas",
    "Isla de la Juventud",
  ],
  "Cape Verde": ["Sal", "Praia", "São Vicente", "Santa Catarina do Fogo"],
  Curacao: ["N/A"],
  "Christmas Island": ["N/A"],
  Cyprus: [
    "Ammochostos",
    "Pafos",
    "Lefkosia",
    "Limassol",
    "Larnaka",
    "Keryneia",
  ],
  "Czech Republic": [
    "Královéhradecký",
    "South Moravian",
    "Zlín",
    "Vysočina",
    "Ústecký",
    "Pardubický",
    "Moravskoslezský",
    "Jihočeský",
    "Olomoucký",
    "Karlovarský",
    "Central Bohemia",
    "Praha",
    "Plzeňský",
    "Liberecký",
  ],
  Germany: [
    "Saxony",
    "Rheinland-Pfalz",
    "North Rhine-Westphalia",
    "Brandenburg",
    "Bavaria",
    "Saxony-Anhalt",
    "Berlin",
    "Lower Saxony",
    "Hesse",
    "Mecklenburg-Vorpommern",
    "Hamburg",
    "Baden-Württemberg",
    "Thuringia",
    "Schleswig-Holstein",
    "Saarland",
    "Bremen",
  ],
  Djibouti: ["Tadjourah", "Obock", "Djibouti", "Ali Sabieh"],
  Denmark: [
    "Central Jutland",
    "South Denmark",
    "Capital Region",
    "Zealand",
    "North Denmark",
  ],
  Dominica: ["Saint George"],
  "Dominican Republic": [
    "Nacional",
    "Santiago",
    "San Cristóbal",
    "El Seíbo",
    "Barahona",
    "San Pedro de Macorís",
    "San Juan",
    "San José de Ocoa",
    "Duarte",
    "Monte Cristi",
    "Puerto Plata",
    "La Altagracia",
    "Hermanas Mirabal",
    "Santiago Rodríguez",
    "Monte Plata",
    "Baoruco",
    "María Trinidad Sánchez",
    "Espaillat",
    "Valverde",
    "La Romana",
    "La Vega",
    "Hato Mayor",
    "Dajabón",
    "Sánchez Ramírez",
    "Monseñor Nouel",
    "Santo Domingo",
    "Peravia",
    "Azua",
  ],
  Algeria: [
    "Boumerdes",
    "Biskra",
    "Tipaza",
    "Relizane",
    "Ouargla",
    "Tlemcen",
    "Tizi Ouzou",
    "Tissemsilt",
    "Tindouf",
    "Adrar",
    "Bejaïa",
    "Tiaret",
    "Aïn Defla",
    "Mila",
    "Tébessa",
    "Batna",
    "Tamanghasset",
    "Skikda",
    "Bouira",
    "Blida",
    "Souk Ahras",
    "Mascara",
    "Oran",
    "Sidi Bel Abbès",
    "Chlef",
    "Mʼsila",
    "Sétif",
    "Saïda",
    "Alger",
    "El Oued",
    "Bordj Bou Arréridj",
    "Oum el Bouaghi",
    "Mostaganem",
    "Ghardaïa",
    "Djelfa",
    "Médéa",
    "Laghouat",
    "Khenchela",
    "Jijel",
    "Guelma",
    "Aïn Temouchent",
    "Constantine",
    "El Tarf",
    "Annaba",
    "El Bayadh",
    "Béchar",
    "Naama النعامة",
  ],
  Ecuador: [
    "Zamora-Chinchipe",
    "Guayas",
    "Los Ríos",
    "Carchi",
    "Napo",
    "Manabí",
    "Santo Domingo de los Tsáchilas",
    "El Oro",
    "Santa Elena",
    "Esmeraldas",
    "Chimborazo",
    "Pichincha",
    "Pastaza",
    "Cotopaxi",
    "Orellana",
    "Tungurahua",
    "Imbabura",
    "Morona-Santiago",
    "Loja",
    "Cañar",
    "Sucumbios",
    "Bolívar",
    "Azuay",
  ],
  Estonia: [
    "Viljandimaa",
    "Tartu",
    "Harjumaa",
    "Ida-Virumaa",
    "Lääne-Virumaa",
    "Pärnumaa",
  ],
  Egypt: [
    "Muḩāfaz̧at al Gharbīyah",
    "Muḩāfaz̧at al Qalyūbīyah",
    "Muḩāfaz̧at al Fayyūm",
    "Muḩāfaz̧at ad Daqahlīyah",
    "Muḩāfaz̧at al Minūfīyah",
    "Sūhāj",
    "Muḩāfaz̧at Banī Suwayf",
    "Kafr ash Shaykh",
    "Al Minyā",
    "Al Buḩayrah",
    "Red Sea",
    "Qinā",
    "Eastern Province",
    "Muḩāfaz̧at Maţrūḩ",
    "Asyūţ",
    "Al Jīzah",
    "Aswān",
    "Cairo Governorate",
    "Dumyāţ",
    "Muḩāfaz̧at Būr Sa‘īd",
    "Al Ismā‘īlīyah",
    "As Suways",
    "Luxor",
    "Muḩāfaz̧at al Wādī al Jadīd",
    "Alexandria",
    "Shamāl Sīnāʼ",
  ],
  "Western Sahara": ["Oued Ed-Dahab-Lagouira"],
  Eritrea: [
    "Northern Red Sea Region",
    "Ānseba",
    "Gash Barka",
    "Maʼākel",
    "Debubawī Kʼeyih Bahrī",
    "Debub",
  ],
  Spain: [
    "Andalusia",
    "Extremadura",
    "Murcia",
    "Valencia",
    "Castille-La Mancha",
    "Canary Islands",
    "Balearic Islands",
    "Melilla",
    "Basque Country",
    "Aragon",
    "Castille and León",
    "Galicia",
    "Madrid",
    "Catalonia",
    "Navarre",
    "Cantabria",
    "Asturias",
    "La Rioja",
    "Ceuta",
  ],
  Ethiopia: [
    "Oromiya",
    "Southern Nations, Nationalities, and People's Region",
    "Amhara",
    "Tigray",
    "Somali",
    "Harari",
    "Gambela",
    "Āfar",
    "Dire Dawa",
    "Bīnshangul Gumuz",
    "Ādīs Ābeba",
  ],
  Finland: [
    "Pirkanmaa",
    "Uusimaa",
    "Northern Savo",
    "Ostrobothnia",
    "Southwest Finland",
    "Lapland",
    "Southern Ostrobothnia",
    "Southern Savonia",
    "Häme",
    "Satakunta",
    "Northern Ostrobothnia",
    "Central Finland",
    "South Karelia",
    "Päijänne Tavastia",
    "Kymenlaakso",
    "Central Ostrobothnia",
    "Kainuu",
    "North Karelia",
  ],
  Fiji: ["Central", "Western", "Northern"],
  "Falkland Islands": ["N/A"],
  Micronesia: ["Pohnpei"],
  "Faroe Islands": ["Streymoy"],
  France: [
    "Île-de-France",
    "Alsace-Champagne-Ardenne-Lorraine",
    "Nord-Pas-de-Calais-Picardie",
    "Auvergne-Rhône-Alpes",
    "Provence-Alpes-Côte d'Azur",
    "Brittany",
    "Aquitaine-Limousin-Poitou-Charentes",
    "Centre",
    "Bourgogne-Franche-Comté",
    "Pays de la Loire",
    "Normandy",
    "Languedoc-Roussillon-Midi-Pyrénées",
    "Corsica",
  ],
  Gabon: [
    "Nyanga",
    "Ogooué-Maritime",
    "Woleu-Ntem",
    "Ngounié",
    "Haut-Ogooué",
    "Estuaire",
    "Moyen-Ogooué",
    "Ogooué-Lolo",
  ],
  "United Kingdom": ["England", "Wales", "Scotland", "Northern Ireland"],
  Grenada: ["Saint George"],
  Georgia: [
    "Samegrelo and Zemo Svaneti",
    "Imereti",
    "Shida Kartli",
    "Abkhazia",
    "Kakheti",
    "T'bilisi",
    "Kvemo Kartli",
    "Guria",
    "Ajaria",
    "Samtskhe-Javakheti",
  ],
  "French Guiana": ["Guyane"],
  Guernsey: ["St Peter Port"],
  Ghana: [
    "Northern",
    "Central",
    "Brong-Ahafo",
    "Upper West",
    "Greater Accra",
    "Western",
    "Ashanti",
    "Eastern",
    "Upper East",
    "Volta",
  ],
  Gibraltar: ["N/A"],
  Greenland: ["Sermersooq"],
  Gambia: ["Western", "North Bank", "Banjul"],
  Guinea: [
    "Labe",
    "Kindia",
    "Kankan",
    "Mamou",
    "Nzerekore",
    "Faranah",
    "Boke",
    "Conakry",
  ],
  Guadeloupe: ["Guadeloupe"],
  "Equatorial Guinea": ["Kié-Ntem", "Bioko Norte", "Litoral"],
  Greece: [
    "Attica",
    "Thessaly",
    "Peloponnese",
    "Central Greece",
    "Crete",
    "Epirus",
    "West Greece",
    "North Aegean",
    "South Aegean",
    "Central Macedonia",
    "East Macedonia and Thrace",
    "West Macedonia",
    "Ionian Islands",
  ],
  "South Georgia and the South Sandwich Islands": ["N/A"],
  Guatemala: [
    "Zacapa",
    "Guatemala",
    "Totonicapán",
    "Chimaltenango",
    "Sacatepéquez",
    "Sololá",
    "Escuintla",
    "Quiché",
    "San Marcos",
    "Suchitepeque",
    "Alta Verapaz",
    "Petén",
    "El Progreso",
    "Baja Verapaz",
    "Retalhuleu",
    "Quetzaltenango",
    "Izabal",
    "Jutiapa",
    "Jalapa",
    "Huehuetenango",
    "Chiquimula",
    "Santa Rosa",
  ],
  Guam: ["Tamuning", "Yigo", "Hagatna", "Dededo", "Mangilao"],
  "Guinea-Bissau": ["Bissau", "Bafatá"],
  Guyana: [
    "East Berbice-Corentyne",
    "Upper Demerara-Berbice",
    "Demerara-Mahaica",
  ],
  "Hong Kong": [
    "Tsuen Wan",
    "Yuen Long",
    "Tuen Mun",
    "Tai Po",
    "Sha Tin",
    "Kowloon City",
    "Central and Western",
  ],
  Honduras: [
    "Cortés",
    "Yoro",
    "Colón",
    "Atlántida",
    "Francisco Morazán",
    "Comayagua",
    "Copán",
    "Santa Bárbara",
    "Valle",
    "La Paz",
    "Olancho",
    "El Paraíso",
    "Choluteca",
  ],
  Croatia: [
    "Zagrebačka",
    "Grad Zagreb",
    "Zadarska",
    "Vukovarsko-Srijemska",
    "Virovitičk-Podravska",
    "Varaždinska",
    "Splitsko-Dalmatinska",
    "Brodsko-Posavska",
    "Požeško-Slavonska",
    "Sisačko-Moslavačka",
    "Šibensko-Kniniska",
    "Primorsko-Goranska",
    "Istarska",
    "Osječko-Baranjska",
    "Koprivničko-Križevačka",
    "Karlovačka",
    "Dubrovačko-Neretvanska",
    "Međimurska",
    "Bjelovarsko-Bilogorska",
  ],
  Haiti: [
    "Artibonite",
    "Ouest",
    "Nord",
    "Nord-Ouest",
    "Nippes",
    "GrandʼAnse",
    "Sud-Est",
    "Centre",
    "Sud",
  ],
  Hungary: [
    "Jász-Nagykun-Szolnok",
    "Borsod-Abaúj-Zemplén",
    "Csongrád",
    "Bekes",
    "Hajdú-Bihar",
    "Szabolcs-Szatmár-Bereg",
    "Heves",
    "Pest",
    "Zala",
    "Veszprém",
    "Komárom-Esztergom",
    "Vas",
    "Tolna",
    "Fejér",
    "Győr-Moson-Sopron",
    "Somogy",
    "Nógrád",
    "Baranya",
    "Bács-Kiskun",
    "Budapest",
  ],
  Indonesia: [
    "North Sumatra",
    "Aceh",
    "Daerah Istimewa Yogyakarta",
    "Central Java",
    "East Java",
    "West Java",
    "South Sulawesi",
    "East Nusa Tenggara",
    "Bali",
    "Maluku",
    "North Sulawesi",
    "Maluku Utara",
    "Lampung",
    "North Kalimantan",
    "Riau Islands",
    "Bangka–Belitung Islands",
    "South Sumatra",
    "Banten",
    "West Kalimantan",
    "Jambi",
    "N/A",
    "West Nusa Tenggara",
    "West Papua",
    "West Sumatra",
    "Central Kalimantan",
    "East Kalimantan",
    "Central Sulawesi",
    "Sulawesi Barat",
    "Riau",
    "Papua",
    "South Kalimantan",
    "Sulawesi Tenggara",
    "Jakarta Raya",
    "Gorontalo",
    "Bengkulu",
  ],
  Ireland: ["Leinster", "Munster", "Connaught", "Ulster"],
  Israel: [
    "Jerusalem",
    "Northern District",
    "Central District",
    "Tel Aviv",
    "Haifa",
    "Southern District",
  ],
  "Isle of Man": ["Douglas"],
  India: [
    "Kashmir",
    "Tamil Nadu",
    "Nagaland",
    "Uttar Pradesh",
    "Telangana",
    "Maharashtra",
    "Karnataka",
    "Andhra Pradesh",
    "Haryana",
    "Rajasthan",
    "Bihar",
    "Madhya Pradesh",
    "Gujarat",
    "Kerala",
    "Goa",
    "Uttarakhand",
    "Himachal Pradesh",
    "Chhattisgarh",
    "Assam",
    "Tripura",
    "Meghalaya",
    "West Bengal",
    "Odisha",
    "Manipur",
    "Punjab",
    "Jharkhand",
    "Dadra and Nagar Haveli",
    "Mizoram",
    "Andaman and Nicobar Islands",
    "Pondicherry",
    "Arunachal Pradesh",
    "NCT",
    "Sikkim",
    "Daman and Diu",
    "Chandigarh",
  ],
  Iraq: [
    "Dahūk",
    "Basra Governorate",
    "Salah ad Din Governorate",
    "Nīnawá",
    "Bābil",
    "Arbīl",
    "Anbar",
    "Diyālá",
    "At Taʼmīm",
    "Karbalāʼ",
    "As Sulaymānīyah",
    "Mayorality of Baghdad",
    "Wāsiţ",
    "Al Muthanná",
    "Al Qādisīyah",
    "Dhi Qar",
    "An Najaf",
    "Maysan",
  ],
  Iran: [
    "Hamadān",
    "Kermānshāh",
    "Lorestān",
    "Semnān",
    "Tehrān",
    "Zanjan",
    "Kohgīlūyeh va Būyer Aḩmad",
    "Golestān",
    "Kerman",
    "Yazd",
    "Razavi Khorasan",
    "Māzandarān",
    "Gīlān",
    "Qazvīn",
    "Āz̄ārbāyjān-e Gharbī",
    "East Azerbaijan",
    "Khuzestan",
    "Khorāsān-e Shomālī",
    "Fars",
    "Chahār Maḩāll va Bakhtīārī",
    "Isfahan",
    "Markazi",
    "Kordestān",
    "Qom",
    "Hormozgan",
    "Khorāsān-e Jonūbī",
    "Ardabīl",
    "Alborz",
    "Īlām",
    "Bushehr",
    "Sistan and Baluchestan",
  ],
  Iceland: ["Northeast", "Capital Region"],
  Italy: [
    "Sicily",
    "Calabria",
    "Sardinia",
    "Apulia",
    "Emilia-Romagna",
    "Lombardy",
    "Veneto",
    "Latium",
    "Campania",
    "Tuscany",
    "Piedmont",
    "Liguria",
    "Abruzzo",
    "Friuli Venezia Giulia",
    "Trentino-Alto Adige",
    "The Marches",
    "Umbria",
    "Molise",
    "Basilicate",
    "Aosta Valley",
  ],
  Jersey: ["St Helier"],
  Jamaica: [
    "Saint Catherine",
    "Westmoreland",
    "Saint Andrew",
    "Saint James",
    "Clarendon",
    "Manchester",
    "Kingston",
  ],
  Jordan: [
    "Amman",
    "Madaba",
    "Ma’an",
    "Irbid",
    "Jerash",
    "Karak",
    "Zarqa",
    "Tafielah",
    "Balqa",
    "Ajlun",
    "Mafraq",
    "Aqaba",
  ],
  Japan: [
    "Wakayama",
    "Kanagawa",
    "Hyōgo",
    "Yamagata",
    "Gifu",
    "Fukuoka",
    "Ibaraki",
    "Saitama",
    "Gunma",
    "Niigata",
    "Tottori",
    "Mie",
    "Shiga Prefecture",
    "Kyoto",
    "Kumamoto",
    "Toyama",
    "Shimane",
    "Ōsaka",
    "Yamaguchi",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Oita",
    "Saga Prefecture",
    "Tokyo",
    "Yamanashi",
    "Nagano",
    "Okayama",
    "Aichi",
    "Ishikawa",
    "Fukui",
    "Miyazaki",
    "Kagawa",
    "Okinawa",
    "Nagasaki",
    "Nara",
    "Akita",
    "Chiba",
    "Kagoshima",
    "Hiroshima",
    "Kochi",
    "Ehime",
    "Fukushima",
    "Miyagi",
    "Iwate",
    "Hokkaido",
    "Aomori",
  ],
  Kenya: [
    "Bungoma",
    "Wajir",
    "Taita Taveta",
    "Nairobi Area",
    "Nakuru",
    "Nyeri",
    "Laikipia",
    "Narok",
    "Kakamega",
    "Kisumu",
    "Marsabit",
    "Mombasa",
    "Migori",
    "Meru",
    "Vihiga",
    "Samburu",
    "Mandera",
    "Kilifi",
    "Makueni",
    "Machakos",
    "Busia",
    "Turkana",
    "Lamu",
    "Kitui",
    "Trans Nzoia",
    "Kisii",
    "Kiambu",
    "Kirinyaga",
    "Kericho",
    "Murang'A",
    "West Pokot",
    "Baringo",
    "Isiolo",
    "Homa Bay",
    "Garissa",
    "Embu",
    "Uasin Gishu",
    "Siaya",
    "Nyandarua",
  ],
  Kyrgyzstan: [
    "Batken",
    "Ysyk-Köl",
    "Chüy",
    "Jalal-Abad",
    "Talas",
    "Osh",
    "Naryn",
    "Bishkek",
    "Osh City",
  ],
  Cambodia: [
    "Phnom Penh",
    "Kandal",
    "Takeo",
    "Svay Rieng",
    "Stung Treng",
    "Banteay Meanchey",
    "Siem Reap",
    "Prey Veng",
    "Pursat",
    "Ŏtâr Méanchey",
    "Preah Vihear",
    "Pailin",
    "Ratanakiri",
    "Koh Kong",
    "Kratie",
    "Kampot",
    "Kampong Thom",
    "Kampong Speu",
    "Preah Sihanouk",
    "Kampong Chhnang",
    "Kampong Cham",
    "Battambang",
  ],
  Kiribati: ["Gilbert Islands"],
  Comoros: ["Anjouan", "Grande Comore"],
  "Saint Kitts and Nevis": ["Saint George Basseterre"],
  "North Korea": [
    "Hwanghae-namdo",
    "Kangwŏn-do",
    "Pyongyang",
    "Hwanghae-bukto",
    "P'yŏngan-namdo",
    "Hamgyŏng-namdo",
    "P'yŏngan-bukto",
    "Rason",
    "Hamgyŏng-bukto",
    "Yanggang-do",
    "Chagang-do",
  ],
  "South Korea": [
    "Gyeongsangbuk-do",
    "Gangwon-do",
    "Jeollanam-do",
    "Chungcheongbuk-do",
    "Gyeonggi-do",
    "Chungcheongnam-do",
    "Gyeongsangnam-do",
    "Jeollabuk-do",
    "Ulsan",
    "Daejeon",
    "Daegu",
    "Seoul",
    "Busan",
    "Gwangju",
    "Incheon",
    "Jeju-do",
  ],
  Kuwait: [
    "Al Farwaniyah",
    "Muḩāfaz̧at Ḩawallī",
    "N/A",
    "Al Aḩmadī",
    "Al Asimah",
    "Al Jahrāʼ",
    "Mubārak al Kabīr",
  ],
  "Cayman Islands": ["George Town"],
  Kazakhstan: [
    "Mangghystaū",
    "Aqtöbe",
    "Atyraū",
    "Batys Qazaqstan",
    "Qaraghandy",
    "East Kazakhstan",
    "Qyzylorda",
    "Qostanay",
    "Zhambyl",
    "Ongtüstik Qazaqstan",
    "Almaty Oblysy",
    "Soltüstik Qazaqstan",
    "Pavlodar",
    "Aqmola",
    "Bayqongyr Qalasy",
    "Astana Qalasy",
    "Almaty Qalasy",
  ],
  Laos: [
    "Vientiane",
    "Houaphan",
    "Savannahkhét",
    "Champasak",
    "Oudômxai",
    "Vientiane Province",
    "Xiangkhoang",
    "Bolikhamsai Province",
    "Khammouan",
    "Louangphabang",
    "Bokeo Province",
  ],
  Lebanon: [
    "Béqaa",
    "Liban-Nord",
    "Liban-Sud",
    "Beyrouth",
    "Mont-Liban",
    "Nabatîyé",
    "Baalbek-Hermel",
  ],
  "Saint Lucia": ["Castries Quarter"],
  Liechtenstein: ["Vaduz"],
  "Sri Lanka": [
    "Western",
    "Southern",
    "Northern Province",
    "Eastern Province",
    "Sabaragamuwa",
    "North Western",
    "Central",
    "Uva",
    "North Central",
  ],
  Liberia: [
    "Grand Gedeh",
    "Nimba",
    "Lofa",
    "Montserrado",
    "Margibi",
    "Maryland",
    "Sinoe",
    "Bong",
    "Grand Bassa",
  ],
  Lesotho: [
    "Quthing",
    "Qachaʼs Nek",
    "Mohaleʼs Hoek",
    "Maseru",
    "Leribe",
    "Mafeteng",
    "Butha-Buthe",
  ],
  Lithuania: [
    "Utenos apskritis",
    "Vilnius County",
    "Telšių apskritis",
    "Tauragės apskritis",
    "Klaipėdos apskritis",
    "Šiaulių apskritis",
    "Panevėžys",
    "Marijampolės apskritis",
    "Kauno apskritis",
    "Alytaus apskritis",
  ],
  Luxembourg: ["Luxembourg"],
  Latvia: [
    "Valmieras Rajons",
    "Ventspils",
    "Liepāja",
    "Tukuma Rajons",
    "Salaspils",
    "Riga",
    "Rēzekne",
    "Ogre",
    "Jūrmala",
    "Jelgava",
    "Jēkabpils Municipality",
    "Daugavpils municipality",
    "Cēsu Rajons",
  ],
  Libya: [
    "Sha‘bīyat al Buţnān",
    "Banghāzī",
    "Darnah",
    "Sha‘bīyat al Wāḩāt",
    "Al Kufrah",
    "Al Marj",
    "Al Jabal al Akhḑar",
    "An Nuqāţ al Khams",
    "Mişrātah",
    "Sha‘bīyat al Jabal al Gharbī",
    "Al Jufrah",
    "Al Marqab",
    "Tripoli",
    "Surt",
    "Az Zāwiyah",
    "Sabhā",
    "Sha‘bīyat Nālūt",
    "Murzuq",
    "Sha‘bīyat Ghāt",
    "Ash Shāţiʼ",
    "Sha‘bīyat Wādī al Ḩayāt",
  ],
  Morocco: [
    "Oriental",
    "Souss-Massa-Drâa",
    "Doukkala-Abda",
    "Taza-Al Hoceima-Taounate",
    "Rabat-Salé-Zemmour-Zaër",
    "Tanger-Tétouan",
    "Guelmim-Es Smara",
    "Gharb-Chrarda-Beni Hssen",
    "Chaouia-Ouardigha",
    "Fès-Boulemane",
    "Grand Casablanca",
    "Meknès-Tafilalet",
    "Marrakech-Tensift-Al Haouz",
    "Tadla-Azilal",
    "Oued ed Dahab-Lagouira",
  ],
  Monaco: [""],
  Moldova: [
    "Raionul Edineţ",
    "Ungheni",
    "Stînga Nistrului",
    "Strășeni",
    "Sîngerei",
    "Raionul Soroca",
    "Orhei",
    "Hînceşti",
    "Căuşeni",
    "Floreşti",
    "Teleneşti",
    "Drochia",
    "Găgăuzia",
    "Chişinău",
    "Cahul",
    "Bender",
    "Bălţi",
  ],
  Montenegro: [
    "Podgorica",
    "Pljevlja",
    "Opština Nikšić",
    "Herceg Novi",
    "Cetinje",
    "Budva",
    "Bijelo Polje",
    "Bar",
  ],
  "Saint Martin": ["N/A"],
  Madagascar: [
    "Atsinanana",
    "Atsimo-Atsinanana",
    "Analanjirofo",
    "Bongolava",
    "Androy",
    "Betsiboka",
    "Atsimo-Andrefana",
    "Anosy",
    "Itasy",
    "Vakinankaratra",
    "Boeny",
    "Sava",
    "Vatovavy Fitovinany",
    "Analamanga",
    "Menabe",
    "Alaotra Mangoro",
    "Melaky",
    "Upper Matsiatra",
    "Ihorombe",
    "Amoron'i Mania",
    "Sofia",
    "Diana",
  ],
  "Marshall Islands": ["Majuro Atoll"],
  Macedonia: [
    "Želino",
    "Vinica",
    "Veles",
    "Tetovo",
    "Tearce",
    "Studeničani",
    "Strumica",
    "Struga",
    "Štip",
    "Karpoš",
    "Saraj",
    "Resen",
    "Radoviš",
    "Prilep",
    "Ohrid",
    "Vrapčište",
    "Negotino",
    "Opstina Lipkovo",
    "Kumanovo",
    "Kriva Palanka",
    "Kočani",
    "Kičevo",
    "Kavadarci",
    "Bogovinje",
    "Gostivar",
    "Gevgelija",
    "Delčevo",
    "Debar",
    "Brvenica",
    "Bitola",
    "Šuto Orizari",
    "Butel",
    "Čair",
    "Ilinden",
    "Kisela Voda",
    "Centar Župa",
  ],
  Mali: [
    "Sikasso",
    "Tombouctou",
    "Ségou",
    "Kayes",
    "Mopti",
    "Koulikoro",
    "Gao",
    "Bamako",
  ],
  Myanmar: [
    "Magway",
    "Ayeyarwady",
    "Mandalay",
    "Yangon",
    "Bago",
    "Mon",
    "Tanintharyi",
    "Shan",
    "Rakhine",
    "Sagain",
    "Kayin",
    "Kachin",
    "Kayah",
    "Chin",
  ],
  Mongolia: [
    "Dzabkhan",
    "Uvs",
    "Bayan-Ölgiy",
    "Hovd",
    "Govĭ-Altay",
    "Ulaanbaatar",
    "Selenge",
    "Hövsgöl",
    "Middle Govĭ",
    "Övörhangay",
    "Orhon",
    "Darhan Uul",
    "Ömnögovĭ",
    "East Gobi Aymag",
    "Bulgan",
    "Bayanhongor",
    "Sühbaatar",
    "Central Aimak",
  ],
  Macao: ["Macau"],
  "Northern Mariana Islands": ["Saipan"],
  Martinique: ["Martinique"],
  Mauritania: [
    "Tiris Zemmour",
    "Trarza",
    "Guidimaka",
    "Nouakchott",
    "Dakhlet Nouadhibou",
    "Hodh ech Chargui",
    "Assaba",
    "Gorgol",
    "Adrar",
    "Brakna",
  ],
  Montserrat: ["Saint Anthony", "Saint Peter"],
  Malta: ["Ħaż-Żabbar", "Il-Belt Valletta", "Qormi", "Il-Mosta", "Birkirkara"],
  Mauritius: [
    "Plaines Wilhems",
    "Pamplemousses",
    "Moka",
    "Port Louis",
    "Grand Port",
    "Rivière du Rempart",
    "Flacq",
  ],
  Maldives: ["Kaafu Atoll"],
  Malawi: ["Northern Region", "Southern Region", "Central Region"],
  Mexico: [
    "Tamaulipas",
    "México",
    "Guerrero",
    "Hidalgo",
    "Puebla",
    "Morelos",
    "Mexico City",
    "Veracruz",
    "Tabasco",
    "Chiapas",
    "Yucatán",
    "Querétaro",
    "San Luis Potosí",
    "Oaxaca",
    "Tlaxcala",
    "Quintana Roo",
    "Nuevo León",
    "Campeche",
    "Sonora",
    "Sinaloa",
    "Jalisco",
    "Baja California",
    "Michoacán",
    "Zacatecas",
    "Guanajuato",
    "Coahuila",
    "Colima",
    "Nayarit",
    "Durango",
    "Baja California Sur",
    "Aguascalientes",
    "Chihuahua",
  ],
  Malaysia: [
    "Kedah",
    "Pahang",
    "Johor",
    "Selangor",
    "Terengganu",
    "Sabah",
    "Labuan",
    "Perak",
    "Kelantan",
    "Negeri Sembilan",
    "Melaka",
    "Penang",
    "Kuala Lumpur",
    "Sarawak",
    "Perlis",
    "Putrajaya",
  ],
  Mozambique: [
    "Gaza",
    "Sofala",
    "Tete",
    "Maputo",
    "Zambézia",
    "Cabo Delgado",
    "Nampula",
    "Inhambane",
    "Maputo City",
    "Niassa",
    "Manica",
  ],
  Namibia: [
    "Zambezi",
    "Khomas",
    "Erongo",
    "Kavango East",
    "Hardap",
    "Otjozondjupa",
    "Oshana",
    "Karas",
    "Omaheke",
  ],
  "New Caledonia": ["South Province"],
  Niger: [
    "Tahoua",
    "Zinder",
    "Tillabéri",
    "Maradi",
    "Niamey",
    "Diffa",
    "Dosso",
    "Agadez",
  ],
  "Norfolk Island": ["N/A"],
  Nigeria: [
    "Kebbi",
    "Niger",
    "Kaduna",
    "Adamawa",
    "Bayelsa",
    "Taraba",
    "Kano",
    "Delta",
    "Nassarawa",
    "Akwa Ibom",
    "Edo",
    "Abia",
    "Cross River",
    "Anambra",
    "Sokoto",
    "Zamfara",
    "Benue",
    "Oyo",
    "Ogun",
    "Yobe",
    "Rivers",
    "Gombe",
    "Kwara",
    "Plateau",
    "Osun",
    "Ondo",
    "Imo",
    "Kogi",
    "Ekiti",
    "Enugu",
    "Borno",
    "Katsina",
    "Lagos",
    "Abuja Federal Capital Territory",
    "Jigawa",
    "Bauchi",
    "Ebonyi",
  ],
  Nicaragua: [
    "Managua",
    "Madriz",
    "Chinandega",
    "Atlántico Norte (RAAN)",
    "Carazo",
    "Rivas",
    "Matagalpa",
    "Atlántico Sur",
    "Nueva Segovia",
    "Granada",
    "León",
    "Masaya",
    "Chontales",
    "Jinotega",
    "Estelí",
    "Boaco",
  ],
  Netherlands: [
    "Overijssel",
    "South Holland",
    "Gelderland",
    "North Brabant",
    "Utrecht",
    "Flevoland",
    "North Holland",
    "Friesland",
    "Groningen",
    "Limburg",
    "Zeeland",
    "Drenthe",
  ],
  Norway: [
    "Sør-Trøndelag",
    "Troms",
    "Vestfold",
    "Nord-Trøndelag",
    "Rogaland",
    "Telemark",
    "Østfold",
    "Oslo",
    "Møre og Romsdal",
    "Nordland",
    "Oppland",
    "Vest-Agder",
    "Buskerud",
    "Hedmark",
    "Hordaland",
    "Aust-Agder",
  ],
  Nepal: [
    "Western Region",
    "Mid Western",
    "Far Western",
    "Eastern Region",
    "Central Region",
  ],
  Nauru: ["Yaren"],
  Niue: ["N/A"],
  "New Zealand": [
    "Wellington",
    "Manawatu-Wanganui",
    "Canterbury",
    "Waikato",
    "Auckland",
    "Taranaki",
    "Nelson",
    "Hawke's Bay",
    "Southland",
    "Otago",
    "Gisborne",
    "Bay of Plenty",
    "Northland",
    "Marlborough",
  ],
  Oman: [
    "Ash Sharqiyah South Governorate",
    "Al Batinah North Governorate",
    "Muḩāfaz̧at ad Dākhilīyah",
    "Z̧ufār",
    "Muḩāfaz̧at Masqaţ",
    "Musandam",
    "Az̧ Z̧āhirah",
    "Ash Sharqiyah North Governorate",
    "Al Batinah South Governorate",
    "Al Buraimi",
  ],
  Panama: [
    "Panamá",
    "Veraguas",
    "Chiriquí",
    "Colón",
    "Herrera",
    "Bocas del Toro",
    "Coclé",
  ],
  Peru: [
    "Loreto",
    "La Libertad",
    "San Martín",
    "Tumbes",
    "Huanuco",
    "Piura",
    "Lambayeque",
    "Ucayali",
    "Amazonas",
    "Cajamarca",
    "Ancash",
    "Puno",
    "Junín",
    "Madre de Dios",
    "Tacna",
    "Lima region",
    "Cusco",
    "Ica",
    "Moquegua",
    "Arequipa",
    "Lima Province",
    "Ayacucho",
    "Huancavelica",
    "Pasco",
    "Callao",
    "Apurímac",
  ],
  "French Polynesia": ["Îles du Vent"],
  "Papua New Guinea": [
    "East Sepik",
    "National Capital",
    "Northern Province",
    "Western Highlands",
    "Southern Highlands",
    "Madang",
    "Morobe",
    "East New Britain",
    "West New Britain",
    "Eastern Highlands",
    "Western Province",
    "Bougainville",
  ],
  Philippines: [
    "Zamboanga Peninsula",
    "Autonomous Region in Muslim Mindanao",
    "Bicol",
    "Ilocos",
    "Western Visayas",
    "Calabarzon",
    "Caraga",
    "Northern Mindanao",
    "Davao",
    "Cagayan Valley",
    "Central Visayas",
    "Central Luzon",
    "Metro Manila",
    "Eastern Visayas",
    "Soccsksargen",
    "Cordillera",
    "Mimaropa",
  ],
  Pakistan: [
    "Sindh",
    "Azad Kashmir",
    "Balochistān",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Islāmābād",
  ],
  Poland: [
    "Masovian Voivodeship",
    "Lublin Voivodeship",
    "Podlasie",
    "Lesser Poland Voivodeship",
    "Łódź Voivodeship",
    "Subcarpathian Voivodeship",
    "Warmian-Masurian Voivodeship",
    "Świętokrzyskie",
    "Silesian Voivodeship",
    "Greater Poland Voivodeship",
    "Lower Silesian Voivodeship",
    "Lubusz",
    "Kujawsko-Pomorskie",
    "Pomeranian Voivodeship",
    "West Pomeranian Voivodeship",
    "Opole Voivodeship",
  ],
  "Saint Pierre and Miquelon": ["Saint-Pierre"],
  Pitcairn: ["N/A"],
  "Puerto Rico": [
    "Aguadilla",
    "Arecibo",
    "Barceloneta",
    "Bayamón",
    "Caguas",
    "Toa Baja",
    "Carolina",
    "Catano",
    "Cayey",
    "Fajardo",
    "Guayama",
    "Guaynabo",
    "Humacao",
    "Manati",
    "Mayaguez",
    "Ponce",
    "San Juan",
    "Trujillo Alto",
    "Vega Baja",
    "Yauco",
  ],
  "Palestinian Territory": ["Gaza Strip", "West Bank"],
  Portugal: [
    "Lisbon",
    "Santarém",
    "Setúbal",
    "Faro",
    "Portalegre",
    "Leiria",
    "Madeira",
    "Évora",
    "Castelo Branco",
    "Beja",
    "Viseu",
    "Vila Real",
    "Porto",
    "Viana do Castelo",
    "Guarda",
    "Aveiro",
    "Braga",
    "Coimbra",
    "Bragança",
    "Azores",
  ],
  Palau: ["Melekeok"],
  Paraguay: [
    "Guairá",
    "Presidente Hayes",
    "Central",
    "Misiones",
    "Alto Paraná",
    "Ñeembucú",
    "Amambay",
    "Itapúa",
    "Caaguazú",
    "Concepción",
    "Caazapá",
    "Cordillera",
    "Asunción",
  ],
  Qatar: [
    "Baladīyat Umm Şalāl",
    "Baladīyat ar Rayyān",
    "Al Wakrah",
    "Al Khawr",
    "Baladīyat ad Dawḩah",
  ],
  Reunion: ["Réunion", "N/A"],
  Romania: [
    "Teleorman",
    "Braşov",
    "Sălaj",
    "Hunedoara",
    "Ilfov",
    "Maramureş",
    "Suceava",
    "Vaslui",
    "Ialomiţa",
    "Cluj",
    "Tulcea",
    "Mureş",
    "Covasna",
    "Neamţ",
    "Gorj",
    "Dâmboviţa",
    "Timiş",
    "Galaţi",
    "Olt",
    "Sibiu",
    "Alba",
    "Satu Mare",
    "Bihor",
    "Vâlcea",
    "Buzău",
    "Caraş-Severin",
    "Prahova",
    "Argeş",
    "Călăraşi",
    "Harghita",
    "Constanța",
    "Bacău",
    "Iaşi",
    "Giurgiu",
    "Vrancea",
    "Dolj",
    "Mehedinţi",
    "Botoşani",
    "Bucureşti",
    "Brăila",
    "Bistriţa-Năsăud",
    "Arad",
  ],
  Serbia: ["Vojvodina", "Central Serbia"],
  Russia: [
    "Tverskaya",
    "St.-Petersburg",
    "Rjazan",
    "Moscow",
    "Rostov",
    "MO",
    "Chelyabinsk",
    "Brjansk",
    "Volgograd",
    "Samara",
    "Tambov",
    "Stavropol'skiy",
    "Kursk",
    "Tatarstan",
    "Karachayevo-Cherkesiya",
    "Nizjnij Novgorod",
    "Penza",
    "Murmansk",
    "Vladimir",
    "Mariy-El",
    "Krasnodarskiy",
    "Saratov",
    "Komi Republic",
    "Lipetsk",
    "Tula",
    "Orenburg",
    "Smolensk",
    "Jaroslavl",
    "Kirov",
    "Bashkortostan",
    "Arkhangelskaya",
    "Adygeya",
    "Leningrad",
    "Udmurtiya",
    "Voronezj",
    "Vologda",
    "Kostroma",
    "North Ossetia",
    "Ivanovo",
    "Perm",
    "Pskov",
    "Belgorod",
    "Novgorod",
    "Chechnya",
    "Ulyanovsk",
    "Kabardino-Balkariya",
    "Ingushetiya",
    "Kaliningrad",
    "Kaluga",
    "Republic of Karelia",
    "Chuvashia",
    "Sverdlovsk",
    "Mordoviya",
    "Orjol",
    "Nenetskiy Avtonomnyy Okrug",
    "Dagestan",
    "Astrakhan",
    "Kalmykiya",
    "Tjumen",
    "Altai Krai",
    "Kemerovo",
    "Krasnoyarskiy",
    "Khanty-Mansiyskiy Avtonomnyy Okrug",
    "Tomsk",
    "Novosibirsk",
    "Irkutsk",
    "Yamalo-Nenetskiy Avtonomnyy Okrug",
    "Omsk",
    "Kurgan",
    "Khakasiya",
    "Altai Republic",
    "Tyva",
    "Amur",
    "Sakha",
    "Khabarovsk Krai",
    "Primorskiy",
    "Respublika Buryatiya",
    "Transbaikal Territory",
    "Jewish Autonomous Oblast",
    "Kamtsjatka",
    "Sakhalin",
    "Magadan",
  ],
  Rwanda: [
    "Eastern Province",
    "Northern Province",
    "Southern Province",
    "Kigali",
    "Western Province",
  ],
  "Saudi Arabia": [
    "Al Madīnah al Munawwarah",
    "Minţaqat Tabūk",
    "Northern Borders",
    "Makkah",
    "Eastern Province",
    "Al Jawf",
    "Jizan",
    "Minţaqat ‘Asīr",
    "Najrān",
    "Ḩāʼil",
    "Al-Qassim",
    "Ar Riyāḑ",
    "Minţaqat al Bāḩah",
  ],
  "Solomon Islands": ["Guadalcanal"],
  Seychelles: ["English River"],
  Sudan: [
    "Central Darfur",
    "Al Jazīrah",
    "Shamāl Kurdufān",
    "Khartoum",
    "Red Sea",
    "White Nile",
    "Sinnār",
    "River Nile",
    "Northern State",
    "Kassala",
    "Southern Kordofan",
    "Al Qaḑārif",
    "Blue Nile",
    "West Kordofan State",
    "Western Darfur",
    "Northern Darfur",
    "Eastern Darfur",
  ],
  Sweden: [
    "Västerbotten",
    "Norrbotten",
    "Skåne",
    "Gotland",
    "Kronoberg",
    "Kalmar",
    "Västmanland",
    "Jönköping",
    "Halland",
    "Västra Götaland",
    "Stockholm",
    "Uppsala",
    "Västernorrland",
    "Gävleborg",
    "Jämtland",
    "Örebro",
    "Södermanland",
    "Östergötland",
    "Värmland",
    "Blekinge",
    "Dalarna",
  ],
  Singapore: ["Central Singapore"],
  "Saint Helena": ["Saint Helena"],
  Slovenia: [
    "Trbovlje",
    "Velenje",
    "Ptuj",
    "Novo Mesto",
    "Maribor",
    "Ljubljana",
    "Kranj",
    "Koper-Capodistria",
    "Celje",
  ],
  "Svalbard and Jan Mayen": ["Svalbard"],
  Slovakia: [
    "Prešovský",
    "Košický",
    "Banskobystrický",
    "Nitriansky",
    "Žilinský",
    "Trnavský",
    "Trenčiansky",
    "Bratislavský",
  ],
  "Sierra Leone": [
    "Western Area",
    "Eastern Province",
    "Northern Province",
    "Southern Province",
  ],
  "San Marino": ["San Marino"],
  Senegal: [
    "Ziguinchor",
    "Kolda",
    "Diourbel",
    "Thiès",
    "Tambacounda",
    "Sédhiou",
    "Saint-Louis",
    "Fatick",
    "Dakar",
    "Kaolack",
    "Louga",
    "Matam",
    "Kédougou",
    "Kaffrine",
  ],
  Somalia: [
    "Lower Shabeelle",
    "Bari",
    "Banaadir",
    "Gedo",
    "Lower Juba",
    "Middle Juba",
    "Middle Shabele",
    "Woqooyi Galbeed",
    "Nugaal",
    "Mudug",
    "Sanaag",
    "Galguduud",
    "Bay",
    "Hiiraan",
    "Togdheer",
    "Sool",
    "Awdal",
  ],
  Suriname: ["Paramaribo", "Wanica"],
  "South Sudan": [
    "Central Equatoria",
    "Western Equatoria",
    "Western Bahr al Ghazal",
    "Northern Bahr al Ghazal",
    "Eastern Equatoria",
    "Warrap",
    "Lakes",
    "Upper Nile",
    "Jonglei",
  ],
  "Sao Tome and Principe": ["São Tomé Island"],
  "El Salvador": [
    "La Paz",
    "Usulután",
    "San Salvador",
    "Sonsonate",
    "Cabañas",
    "San Vicente",
    "Santa Ana",
    "San Miguel",
    "Cuscatlán",
    "Morazán",
    "La Libertad",
    "La Unión",
    "Chalatenango",
    "Ahuachapán",
  ],
  "Sint Maarten": ["N/A"],
  Syria: [
    "Rif-dimashq",
    "Hama",
    "Tartus",
    "Aleppo",
    "Homs",
    "Daraa",
    "Deir ez-Zor",
    "Idlib",
    "Latakia",
    "Dimashq",
    "Al-Hasakah",
    "Ar-Raqqah",
    "As-Suwayda",
    "Quneitra",
  ],
  Swaziland: ["Hhohho", "Manzini"],
  "Turks and Caicos Islands": ["N/A"],
  Chad: [
    "Ennedi-Ouest",
    "Salamat",
    "Ouaddaï",
    "Moyen-Chari",
    "Mayo-Kebbi Ouest",
    "Batha",
    "Chari-Baguirmi",
    "Barh el Gazel",
    "Logone Occidental",
    "Guéra",
    "Hadjer-Lamis",
    "Kanem",
    "Tandjilé",
    "Mandoul",
    "Logone Oriental",
    "Mayo-Kebbi Est",
  ],
  "French Southern Territories": ["Kerguelen"],
  Togo: ["Maritime", "Centrale", "Plateaux", "Kara", "Savanes"],
  Thailand: [
    "Phuket",
    "Prachuap Khiri Khan",
    "Phetchaburi",
    "Trang",
    "Nakhon Si Thammarat",
    "Lampang",
    "Uthai Thani",
    "Kanchanaburi",
    "Tak",
    "Surat Thani",
    "Sukhothai",
    "Chiang Mai",
    "Ratchaburi",
    "Ranong",
    "Phayao",
    "Lamphun",
    "Chiang Rai",
    "Nakhon Sawan",
    "Chumphon",
    "Krabi",
    "Kamphaeng Phet",
    "Kalasin",
    "Changwat Udon Thani",
    "Songkhla",
    "Nakhon Ratchasima",
    "Samut Prakan",
    "Changwat Nong Bua Lamphu",
    "Yasothon",
    "Pattani",
    "Yala",
    "Ang Thong",
    "Phetchabun",
    "Changwat Ubon Ratchathani",
    "Loei",
    "Phra Nakhon Si Ayutthaya",
    "Sa Kaeo",
    "Uttaradit",
    "Trat",
    "Phichit",
    "Chanthaburi",
    "Nong Khai",
    "Narathiwat",
    "Surin",
    "Suphan Buri",
    "Sisaket",
    "Chon Buri",
    "Sing Buri",
    "Changwat Bueng Kan",
    "Sakon Nakhon",
    "Satun",
    "Sara Buri",
    "Samut Songkhram",
    "Samut Sakhon",
    "Nakhon Pathom",
    "Roi Et",
    "Rayong",
    "Buriram",
    "Prachin Buri",
    "Chaiyaphum",
    "Phrae",
    "Phitsanulok",
    "Phatthalung",
    "Chachoengsao",
    "Pathum Thani",
    "Nonthaburi",
    "Nan",
    "Nakhon Phanom",
    "Nakhon Nayok",
    "Mukdahan",
    "Maha Sarakham",
    "Lop Buri",
    "Bangkok",
    "Khon Kaen",
    "Chai Nat",
    "Amnat Charoen",
  ],
  Tajikistan: [
    "Khatlon",
    "Viloyati Sughd",
    "Republican Subordination",
    "Gorno-Badakhshan",
    "Dushanbe",
  ],
  "East Timor": [
    "Cova Lima",
    "Liquiçá",
    "Bobonaro",
    "Díli",
    "Baucau",
    "Aileu",
    "Manufahi",
    "Lautém",
  ],
  Turkmenistan: ["Balkan", "Ahal", "Daşoguz", "Mary", "Lebap"],
  Tunisia: [
    "Zaghwān",
    "Tūnis",
    "Tawzar",
    "Tataouine",
    "Al Qaşrayn",
    "Nābul",
    "Kef",
    "Sūsah",
    "Silyānah",
    "Sīdī Bū Zayd",
    "Al Munastīr",
    "Şafāqis",
    "Al Mahdīyah",
    "Qibilī",
    "Ariana",
    "Gafsa",
    "Qābis",
    "Madanīn",
    "Banzart",
    "Manouba",
    "Bājah",
    "Jundūbah",
    "Bin ‘Arūs",
    "Al Qayrawān",
  ],
  Tonga: ["Tongatapu"],
  Turkey: [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Düzce",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Iğdır",
    "Isparta",
    "İstanbul",
    "İzmir",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırıkkale",
    "Kırklareli",
    "Kırşehir",
    "Kilis",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Şanlıurfa",
    "Şırnak",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
  ],
  "Trinidad and Tobago": [
    "Tunapuna/Piarco",
    "Tobago",
    "Sangre Grande",
    "City of San Fernando",
    "Mayaro",
    "City of Port of Spain",
    "Point Fortin",
    "San Juan/Laventille",
    "Chaguanas",
    "Borough of Arima",
  ],
  Tuvalu: ["Funafuti"],
  Taiwan: ["Taiwan", "Taipei", "Kaohsiung", "Fukien"],
  Tanzania: [
    "Zanzibar Urban/West",
    "Pemba North",
    "Mbeya",
    "Pwani",
    "Geita",
    "Kigoma",
    "Katavi",
    "Mwanza",
    "Arusha",
    "Tabora",
    "Shinyanga",
    "Mara",
    "Tanga",
    "Rukwa",
    "Simiyu",
    "Zanzibar Central/South",
    "Singida",
    "Kilimanjaro",
    "Kagera",
    "Njombe",
    "Morogoro",
    "Manyara",
    "Dodoma",
    "Ruvuma",
    "Dar es Salaam",
    "Iringa",
    "Lindi",
    "Pemba South",
    "Mtwara",
  ],
  Ukraine: [
    "Sumy",
    "Donetsk",
    "Zaporizhia",
    "Cherkasy",
    "Lviv",
    "Kirovohrad",
    "Kharkiv",
    "Zhytomyr",
    "Vinnyts'ka",
    "Dnipropetrovsk",
    "Rivne",
    "Odessa",
    "Crimea",
    "Kiev",
    "Zakarpattia",
    "Mykolaiv",
    "Volyn",
    "Kherson",
    "Ternopil",
    "Luhansk",
    "Khmelnytskyi",
    "Misto Sevastopol’",
    "Chernihiv",
    "Poltava",
    "Ivano-Frankivsk",
    "Kyiv City",
    "Chernivtsi",
  ],
  Uganda: [
    "Northern Region",
    "Central Region",
    "Eastern Region",
    "Western Region",
  ],
  "United States": [
    "Virginia",
    "Alabama",
    "Kentucky",
    "Arkansas",
    "Washington, D.C.",
    "Delaware",
    "Florida",
    "Georgia",
    "Illinois",
    "Indiana",
    "Kansas",
    "Louisiana",
    "Maryland",
    "Missouri",
    "Mississippi",
    "North Carolina",
    "New Jersey",
    "Ohio",
    "Oklahoma",
    "Pennsylvania",
    "South Carolina",
    "Tennessee",
    "Texas",
    "Connecticut",
    "Iowa",
    "Massachusetts",
    "Maine",
    "Michigan",
    "Minnesota",
    "North Dakota",
    "Nebraska",
    "New Hampshire",
    "New York",
    "Rhode Island",
    "South Dakota",
    "Vermont",
    "Wisconsin",
    "West Virginia",
    "California",
    "Arizona",
    "Colorado",
    "New Mexico",
    "Nevada",
    "Utah",
    "Alaska",
    "Idaho",
    "Montana",
    "Oregon",
    "Washington",
    "Wyoming",
    "Hawaii",
  ],
  Uruguay: [
    "Río Negro",
    "Flores",
    "Treinta y Tres",
    "Tacuarembó",
    "Canelones",
    "San José",
    "Maldonado",
    "Salto",
    "Rocha",
    "Rivera",
    "Paysandú",
    "Montevideo",
    "Lavalleja",
    "Soriano",
    "Cerro Largo",
    "Florida",
    "Durazno",
    "Colonia",
    "Artigas",
  ],
  Uzbekistan: [
    "Karakalpakstan",
    "Jizzax",
    "Samarqand",
    "Surxondaryo",
    "Qashqadaryo",
    "Bukhara",
    "Toshkent",
    "Fergana",
    "Sirdaryo",
    "Navoiy",
    "Namangan",
    "Xorazm",
    "Toshkent Shahri",
    "Andijon",
  ],
  Vatican: ["N/A"],
  "Saint Vincent and the Grenadines": ["Saint George"],
  Venezuela: [
    "Nueva Esparta",
    "Anzoátegui",
    "Barinas",
    "Guárico",
    "Yaracuy",
    "Aragua",
    "Portuguesa",
    "Trujillo",
    "Carabobo",
    "Bolívar",
    "Delta Amacuro",
    "Cojedes",
    "Táchira",
    "Miranda",
    "Zulia",
    "Lara",
    "Falcón",
    "Amazonas",
    "Mérida",
    "Vargas",
    "Sucre",
    "Capital",
    "Monagas",
    "Apure",
  ],
  "British Virgin Islands": ["N/A"],
  "U.S. Virgin Islands": ["Saint Thomas Island", "Saint Croix Island"],
  Vietnam: [
    "Nghệ An",
    "Yên Bái",
    "Bà Rịa-Vũng Tàu",
    "Hau Giang",
    "Vĩnh Phúc",
    "Vĩnh Long",
    "Phú Thọ",
    "Quảng Ninh",
    "Phú Yên",
    "Tuyên Quang",
    "Trà Vinh",
    "Bình Dương",
    "Ho Chi Minh City",
    "Thanh Hóa",
    "Thái Nguyên",
    "Thái Bình",
    "Tây Ninh",
    "Long An",
    "Quảng Nam",
    "Ha Nội",
    "Sơn La",
    "Sóc Trăng",
    "Lào Cai",
    "Đồng Tháp",
    "Kiến Giang",
    "Bình Định",
    "Quảng Ngãi",
    "Gia Lai",
    "Hà Nam",
    "Bình Thuận",
    "Ninh Thuận",
    "Ninh Bình",
    "Khánh Hòa",
    "Nam Định",
    "Tiền Giang",
    "An Giang",
    "Lạng Sơn",
    "Kon Tum",
    "Hưng Yên",
    "Thừa Thiên-Huế",
    "Hòa Bình",
    "Hà Tĩnh",
    "Hải Phòng",
    "Hải Dương",
    "Hà Giang",
    "Bình Phước",
    "Quảng Bình",
    "Quảng Trị",
    "Tỉnh Ðiện Biên",
    "Đà Nẵng",
    "Lâm Đồng",
    "Cao Bằng",
    "Cần Thơ",
    "Cà Mau",
    "Ðắc Lắk",
    "Đồng Nai",
    "Bến Tre",
    "Bắc Ninh",
    "Bạc Liêu",
    "Bắc Giang",
    "Bắc Kạn",
  ],
  Vanuatu: ["Shefa"],
  "Wallis and Futuna": ["Circonscription d'Uvéa"],
  Samoa: ["Tuamasaga"],
  Kosovo: [
    "Mitrovica",
    "Gjilan",
    "Ferizaj",
    "Prizren",
    "Pristina",
    "Pec",
    "Gjakova",
  ],
  Yemen: [
    "Abyan",
    "Muḩāfaz̧at al Ḩudaydah",
    "Ibb",
    "Ta‘izz",
    "Sanaa",
    "Şa‘dah",
    "Ma’rib",
    "Laḩij",
    "Ḩajjah",
    "Dhamār",
    "Shabwah",
    "Omran",
    "Muḩāfaz̧at Ḩaḑramawt",
    "Al Jawf",
    "Al Bayḑāʼ",
    "Aden",
  ],
  Mayotte: ["Mamoudzou", "Dzaoudzi", "Koungou"],
  "South Africa": [
    "Gauteng",
    "North-West",
    "Mpumalanga",
    "Orange Free State",
    "Northern Cape",
    "Limpopo",
    "KwaZulu-Natal",
    "Eastern Cape",
    "Western Cape",
  ],
  Zambia: [
    "Luapula",
    "Northern",
    "Southern",
    "Western",
    "Eastern",
    "Copperbelt",
    "Central",
    "Lusaka",
    "North-Western",
  ],
  Zimbabwe: [
    "Masvingo",
    "Matabeleland North",
    "Midlands",
    "Manicaland",
    "Mashonaland West",
    "Mashonaland East",
    "Harare",
    "Bulawayo",
    "Mashonaland Central",
    "Matabeleland South",
  ],
} as const;

export default citiesByCountry;

export type Country = keyof typeof citiesByCountry;
